# .github/workflows
name: Build/Update data compilation file(s) and deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '*.xml'
      - '*.jpg'
      - '*.jpeg'
      - '*.png'
      - '*.gif'
      - '*.css'
      - '*.dtd'
      - '*.xsl'
      - '*.html'

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

env:
  target_file: bahnhof.json

jobs:
  build_update_compilation_files:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository content to github runner.
      - name: Checkout repository content
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - name: Restore file meta data (last change)
        run: perl .github/scripts/git-store-meta.pl --apply

      - name: Listing
        run: |
          ls -la ${{ github.workspace }}

      - name: Check for file meta data changes in repo
        run: perl .github/scripts/git-store-meta.pl --store

      - name: Listing
        run: |
          ls -la ${{ github.workspace }}

      - name: Setup Python Version
        uses: actions/setup-python@v5
        with:
          python-version: 3.8 # Install the python version needed

      # Run build_update_json.py file
      # building/updating {{ target_file }} in {{ github.workspace }}
      - name: Execute Python script
        run: python .github/scripts/build_update_json.py -o ${{ env.target_file }} ${{ github.workspace }}

      - name: Check git status
        run: |
          git status

      # https://github.com/stefanzweifel/git-auto-commit-action
      # authentication done via runner checkout token
      - name: Commit changes on data compilations back to repository
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Apply generated data compilation changes

  # Build job
  build:
    # Add a dependency to the build update compilation files job
    needs: build_update_compilation_files
    # Specify runner + build step
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
      - name: Setup Pages
        id: pagessetup
        uses: actions/configure-pages@v4
      - name: Replace base url using production
        run: sed -i "s|const baseUrl = '';|const baseUrl = '${{ steps.pagessetup.outputs.base_url }}/';|g" index.html
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  # Deployment job
  deploy:
    # Add a dependency to the build job
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
