# .github/workflows
name: Build/Update data compilation file(s) and deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '*.xml'
      - '*.jpg'
      - '*.jpeg'
      - '*.png'
      - '*.gif'
      - '*.svg'
      - '*.css'
      - '*.dtd'
      - '*.xsl'
      - '*.html'

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

env:
  target_file: bahnhof.json

jobs:
  build_update_compilation_files:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository content to github runner.
      - name: Checkout repository content
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2
        with:
          ref: ${{ github.ref_name }}

      - name: Restore file meta data (last change)
        run: perl .github/scripts/git-store-meta.pl --apply

      - name: Listing
        run: |
          ls -la ${{ github.workspace }}

      - name: Setup Python Version
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 #v6.2.0
        with:
          python-version: 3.8 # Install the python version needed

      #- name: Check and correct files last change time due to reference file
      #  run: python .github/scripts/validate-correct-file-mtime.py -v -r ${{ env.target_file }}

      # Run build_update_json.py file
      # building/updating {{ target_file }} in {{ github.workspace }}
      - name: Execute Python script
        run: python .github/scripts/build_update_json.py -o ${{ env.target_file }} ${{ github.workspace }}

      - name: Check for file meta data changes in repo
        run: perl .github/scripts/git-store-meta.pl --store

      - name: Listing
        run: |
          ls -la ${{ github.workspace }}

      - name: Check git status
        run: |
          git status

      # https://github.com/stefanzweifel/git-auto-commit-action
      # authentication done via runner checkout token
      - name: Commit changes on data compilations back to repository
        uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9 #v7.1.0
        with:
          commit_message: Apply generated data compilation changes

  # Build job
  build:
    # Add a dependency to the build update compilation files job
    needs: build_update_compilation_files
    # Specify runner + build step
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository content
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2
        with:
          ref: ${{ github.ref_name }}
      - name: Setup Pages
        id: pagessetup
        uses: actions/configure-pages@45bfe0192ca1faeb007ade9deae92b16b8254a0d #v6.0.0
      - name: Setup Python Version
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 #v6.2.0
        with:
          python-version: 3.9 # Install the python version needed
          # cache: 'pip'
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install lxml
      - name: Execute Python script for Yellow Pages JSON generation (Distribution)
        run: python .github/scripts/build_yellowpage_json.py ${{ github.workspace }}
      - name: Execute Python script for Yellow Pages JSON generation (Receiving)
        run: python .github/scripts/build_yellowpage_json.py -t empfang ${{ github.workspace }}
      # building html files using transformation xml + xslt in {{ github.workspace }}
      - name: Execute Python script for HTML files generation
        run: python .github/scripts/build_update_html.py ${{ github.workspace }}
      - name: Download yellow pages application
        uses: dsaltares/fetch-gh-release-asset@aa2ab1243d6e0d5b405b973c89fa4d06a2d0fff7 #v1.1.2
        with:
          repo: 'fktt-module/web-apps'
          file: 'gelbe-seiten-2.1.0.zip'
          target: '_gs/_gs.zip'
      - name: Prepare yellow pages application
        run: |
          unzip _gs/_gs.zip -d _gs
          cp _gs/gelbe-seiten-base64.html gelbe-seiten.html
      - name: Create Archive including all files for local view
        run: |
          python -m zipfile -c datenblaetter_gelbe-seiten.zip *.xml *.jpeg *.svg *.png *.jpg *.gif *.html bahnhof.* bahnhof_*.xsl GelbeSeiten*.json
      - name: Insert base url of github page inside index.html
        # run: sed -i "s|const baseUrl = '';|const baseUrl = '${{ steps.pagessetup.outputs.base_url }}/';|g" index.html
        run: |
          sed -i 's|data-json-or-url="bahnhof.json"|data-json-or-url="${{ steps.pagessetup.outputs.base_url }}/bahnhof.json"|g' index.html
          sed -i 's|data-zip-file="datenblaetter_gelbe-seiten.zip"|data-zip-file="${{ steps.pagessetup.outputs.base_url }}/datenblaetter_gelbe-seiten.zip"|g' index.html
          sed -i 's|data-yellow-pages="gelbe-seiten.html"|data-yellow-pages="${{ steps.pagessetup.outputs.base_url }}/gelbe-seiten.html"|g' index.html
          sed -i 's|data-versand-url="GelbeSeitenVersand.json"|data-versand-url="${{ steps.pagessetup.outputs.base_url }}/GelbeSeitenVersand.json"|g' gelbe-seiten.html
          sed -i 's|data-empfang-url="GelbeSeitenEmpfang.json"|data-empfang-url="${{ steps.pagessetup.outputs.base_url }}/GelbeSeitenEmpfang.json"|g' gelbe-seiten.html
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@44a6e6beabd48582f863aeeb6cb2151cc1716697 #v1.0.13
        with:
          source: ./
          destination: ./_site
      - name: Upload artifact
        uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b #v4.0.0

  # Deployment job
  deploy:
    # Add a dependency to the build job
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 #v5.0.0
